'use client'

/**
 * LeadForm — pre-configured embed component.
 *
 * Generated by the Form Builder embed page. Copy this file into your project.
 * No other dependencies required beyond React.
 *
 * Usage — just drop it in, no props needed:
 *   import { LeadForm } from './LeadForm'
 *   <LeadForm />
 *
 * Attribution (vendorId / subId) is read automatically from the page URL:
 *   yourpage.com/?vendor_id=YOUR_VID&sub_id=YOUR_SUB_ID&lead_mode=1&z1=Z1&z2=Z2
 */

import { useEffect, useRef } from 'react'

// ── Pre-configured by Form Builder ────────────────────────────────────────────
const TOKEN = '1463d112-fe60-4125-a096-c7224f69f6ea'
const EMBED_ORIGIN = 'https://reports.astoriacompany.com'
// ─────────────────────────────────────────────────────────────────────────────

const SCRIPT_ID = 'le-form-js'

function deriveApiUrl(frontendUrl: string): string {
  try {
    const url = new URL(frontendUrl)
    if (url.hostname.endsWith('.localhost')) {
      return `${url.protocol}//${url.hostname}:8000`
    }
    const parts = url.hostname.split('.')
    if (parts.length >= 2) parts[0] = 'backend'
    return `${url.protocol}//${parts.join('.')}`
  } catch {
    return frontendUrl
  }
}

interface LeadFormProps {
  className?: string
  onSuccess?: () => void
  onRedirect?: (url: string) => void
}

export function LeadForm({ className, onSuccess, onRedirect }: LeadFormProps) {
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    function handler(e: Event) {
      const detail = (e as CustomEvent<{ form_token: string; redirect_url?: string }>).detail
      if (detail?.form_token !== TOKEN) return
      if (detail?.redirect_url) {
        onRedirect?.(detail.redirect_url)
      } else {
        onSuccess?.()
      }
    }
    window.addEventListener('le:submitted', handler)
    return () => window.removeEventListener('le:submitted', handler)
  }, [onSuccess, onRedirect])

  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    // Read attribution params from the page URL — set by your ad platform
    const params = new URLSearchParams(window.location.search)
    const vendorId = params.get('vendor_id') ?? undefined
    const subId = params.get('sub_id') ?? undefined
    const leadMode = params.get('lead_mode') ?? '1'
    const z1 = params.get('z1') ?? undefined
    const z2 = params.get('z2') ?? undefined

    const apiUrl = deriveApiUrl(EMBED_ORIGIN)

    const trigger = document.createElement('script')
    trigger.setAttribute('data-token', TOKEN)
    if (vendorId) trigger.setAttribute('data-vendor-id', vendorId)
    if (subId) trigger.setAttribute('data-sub-id', subId)
    if (z1) trigger.setAttribute('data-z1', z1)
    if (z2) trigger.setAttribute('data-z2', z2)
    trigger.setAttribute('data-tier', 'ALL')
    trigger.setAttribute('data-lead-mode', leadMode)
    trigger.setAttribute('data-backend-url', apiUrl)
    container.appendChild(trigger)

    function mount() {
      ; (window as any).LeadExchange?.mount(trigger)
    }

    if ((window as any).LeadExchange?.mount) {
      mount()
    } else if (!document.getElementById(SCRIPT_ID)) {
      const s = document.createElement('script')
      s.id = SCRIPT_ID
      s.src = `${EMBED_ORIGIN}/embed/form.js`
      s.async = true
      s.onload = () => { if (!trigger.getAttribute('data-le-initialized')) mount() }
      document.head.appendChild(s)
    } else {
      document.getElementById(SCRIPT_ID)!.addEventListener('load', mount, { once: true })
    }

    return () => {
      const host = container.querySelector('[data-le-host]') as HTMLElement | null
      if (host && (host as any).__leHost) {
        ; (host as any).__leRoot?.unmount()
        host.remove()
      }
      container.innerHTML = ''
    }
  }, [])

  return <div ref={containerRef} className={className} />
}
